Mamba tests
hpi-sam/ask-your-repository-api pull request #21
Opened 2018-12-04 18:09 UTC by Adrian-St

Adds 100% test coverage and some abstraction.

2018-12-05 13:01 UTC, Askir requested changes
Most importantly I'd like to have the elasticsearc response factory for testing. And an explanation as why the decorator thing actually works. Everything else is just additional and nice to have.

2018-12-05 13:01 UTC, Askir commented on application/base.py
> +            list(set(cls.member_decorators) - set(cls.method_decorators))
what exactly do these two lines do? What does the backslash do? And why do we add the method decorators and then subtract them again? Looks like gibberish to me, maybe a comment would also be nice :D

2018-12-05 13:01 UTC, Askir commented on application/controllers/artifacts_controller.py
> -            return {"error": "search engine not available"}, 503
removing all this code duplication is amazing for sure!

2018-12-05 13:01 UTC, Askir commented on application/controllers/artifacts_controller.py
> +            new_list = existing_tags + list(set(params["tags"]) - set(existing_tags))
Can't you just call set() again to make everything unique instead of doing `-set(existing_tags)`?

2018-12-05 13:01 UTC, Askir commented on application/models/esmodel.py
> +        return self, 201
Why exactly did you remove the try catch here? There had to be a reason for it before no?

2018-12-05 13:01 UTC, Askir commented on application/controllers/artifacts_controller.py
> +    method_decorators = [check_es]
I don't quite get how this results in check_es being called before the execution of every method. Do you have a link that I could read up on? Is method_decorators a special keyword? Probably not but how exactly does the code in base.py ensure the calling? I'm confused by all this meta programming :D

2018-12-05 13:01 UTC, Askir commented on specs/models/esmodel_spec.py
> +            expect(lambda: self.es_model.update({})).to(raise_error(NotInitialized))
Testing the ESModel without an ES connection for sure is annoying.

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +    # pylint: disable=duplicate-code
Does it really complain about this? oof, we really need to figure out how to use pylint effectively. There have to be some better presets.

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +                                 "file_date": "yesterday"}}]}})
Can we extract this JSON into a test helper for elastic search responses? Like basically an elastic_search_response_factory. I think they'll be useful later on and reading something like `es_response_factory.list_of_artifacts(2)` is more readable than 20 lines of json.

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +                    expect(self.response.json).to(have_key("file_url"))
If we do this thourougly our tests could just be our API documentation. We just have to link the files in the correct places. These would at least always be up to date, although they don't quite contain the amount of example that I would wish for in a documentation.

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +                    expect(self.response.status_code).to(equal(400))
why is this not a 422?

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +                    expect(self.response.status_code).to(equal(400))
Again a 400 that is rather unspecific.

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +    with description('/1'):
can we rename this to '/:id' ?

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +                                             "file_date": "today"}})
Another elastic search response for our factory ;)

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +                                             "file_date": "today"}})
More jsons for our factory <3

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +                                                               ]})
You actually test if it appends, nice!

2018-12-05 13:01 UTC, Askir commented on specs/requests/artifacts_spec.py
> +                expect(self.response.status_code).to(equal(200))
This doesn'T check for the response format and also doesn't check if offset, limit and search term have been passed correctly.

2018-12-06 10:44 UTC, Adrian-St commented on application/base.py
> +            list(set(cls.member_decorators) - set(cls.method_decorators))
this adds the list of member_decorators(decorators that are only called on all members) to the list of all method decorators. The `/` is there to break the line into two lines. I will add a comment :D

2018-12-06 10:45 UTC, Adrian-St commented on application/base.py
> +            list(set(cls.member_decorators) - set(cls.method_decorators))
and we use the subtraction of sets to eliminate duplicates

2018-12-06 10:48 UTC, Adrian-St commented on application/controllers/artifacts_controller.py
> +            new_list = existing_tags + list(set(params["tags"]) - set(existing_tags))
Unfortunately just calling list(set()) somehow gives you a non-determenistic ordering (don't ask me why :D) which is hard to test. Also it kind of makes sense to always have the existing tags first.

2018-12-06 10:50 UTC, Adrian-St commented on application/models/esmodel.py
> +        return self, 201
before I used `es.create`, which gives you a conflict error if the object with that id already exists. Now we use `index` in the save method, which will replace an existing one.

2018-12-06 10:56 UTC, Adrian-St commented on application/controllers/artifacts_controller.py
> +    method_decorators = [check_es]
you can define method_decorators on resources with flask-restful [flask-restful](https://flask-restful.readthedocs.io/en/latest/extending.html#resource-method-decorators). I'm just adding that to the Resource in base.

2018-12-06 10:58 UTC, Adrian-St commented on specs/requests/artifacts_spec.py
> +    # pylint: disable=duplicate-code
It actually doesn't anymore, I just removed the __init__.py, so they are not in the same package anymore. We have to find a solution if we need packages though.

2018-12-06 11:00 UTC, Adrian-St commented on specs/requests/artifacts_spec.py
> +                    expect(self.response.status_code).to(equal(400))
Ask flask.restful :D

2018-12-06 11:01 UTC, Adrian-St commented on specs/requests/artifacts_spec.py
> +                    expect(self.response.status_code).to(equal(400))
I can return a 422 here

2018-12-06 12:53 UTC, Askir approved these changes
Thanks for the changes
, looks much better. I have checked on the input validation. Apparently reqparser is deprecated instead we should use marshmallow. I've already started a branch that changes this which will fix the 400 422 error code thing. Tests are still very long wonder if we should split it into more files? 300 lines aint no joke.  
Anyways looks good to me for now!

2018-12-06 13:23 UTC, merged