Multi Tagging
hpi-sam/ask-your-repository-api pull request #49
Opened 2019-01-21 20:05 UTC by erksch

2019-01-21 20:15 UTC, erksch commented
I'm sorry tests are on the way :/

2019-01-21 20:34 UTC, erksch commented
How about `PUT /tags/multi` or `PUT /multiTags`

2019-01-22 10:09 UTC, Adrian-St requested changes

2019-01-22 10:09 UTC, Adrian-St commented on application/controllers/tags_controller.py
> +        new_multi_tags = list(params["tags"])
params["tags"] should be a list already, no need to convert again.

2019-01-22 10:09 UTC, Adrian-St commented on application/controllers/tags_controller.py
> +        for object_id in set(params["ids"]):
Please use Artifact.find_all instead.
Elasticsearch uses mget for multiple id's

2019-01-22 10:09 UTC, Adrian-St commented on application/controllers/tags_controller.py
> +                    existing_multi_tags = list(set(existing_multi_tags) & set(artifact.tags))
Why do you always convert to list?
I think it would be better to initialize existiting_multi_tags as an empty set.

2019-01-22 18:24 UTC, erksch commented
Thanks for taking a look, but I discussed my frontend approach with Arne and would favour deprecating this change. Stay tuned for my other approach.

2019-01-22 18:24 UTC, closed without merging